name: deploy-test
on:
  push:
      branches:
        - 'test'

env:
    NX_FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
    NX_FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
    NX_FIREBASE_KEY: ${{secrets.FIREBASE_KEY}}
    NX_FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
    NX_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
    NX_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
    NX_FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
    FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN_PRD}}

jobs:
  nest:
    name: "Prueba, linting y construcción de la API."
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.16.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          npm: 'cache'
      - name: Install Dependencies  
        run: npm install
      - name: Testing
        run: npx nx test api --no-cloud
      - name: Prueba de linting
        run: npx nx lint api --no-cloud
      - name: Construccion de la aplicacion
        run: npx nx build api --no-cloud
  react-clientes:
    name: "Pruebas, linting y construccion del frontend de clientes."
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          npm: 'cache'
      - name: Install Dependencies  
        run: npm install
      - name: Testing
        run: npx nx test client --no-cloud
      - name: Prueba de linting
        run: npx nx lint client --no-cloud
      - name: Construccion de la aplicacion
        run: npx nx build client --no-cloud
      - name: Dependencia para hacer deploy en firebase
        run: npm install -g firebase-tools 
      - name: Despliegue a firebase 
        run: npx nx deploy client --no-cloud
  react-administrador:
    name: "Pruebas, linting y construccion del frontend de administrador."
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          npm: 'cache'
      - name: Install Dependencies  
        run: npm install
      - name: Testing
        run: npx nx test admin --no-cloud
      - name: Prueba de linting
        run: npx nx lint admin --no-cloud
      - name: Construccion de la aplicacion
        run: npx nx build admin --no-cloud
      - name: Dependencia para hacer deploy en firebase
        run: npm install -g firebase-tools 
      - name: Despliegue a firebase
        run : npx nx deploy admin --no-cloud
       