name: pipeline-test
on:
  push:
      branches:
        - 'develop'

jobs:
  react-clientes:
    name: "Pruebas, linting y colnstruccion del frontend de clientes."
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.16.1]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies  
        run: npm install
      - name: Construccion de la aplicacion
        run: npx nx build client
      - name: Dependencia para hacer deploy en firebase
        run: npm install -g firebase-tools 
      - name: Despliegue a firebase 
        run: |
          cd client-build && firebase deploy --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PRD }}
      
      
