name: pipeline-test
on:
  push:
      branches:
        - 'develop'

jobs:
  nest:
    name: "Prueba, linting y construcción de la API."
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [18.16.1]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies  
        run: npm install

      - run: npx nx run api:test
      - run: npx nx run api:lint
      - run: npx nx run api:build